spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/flowfully-user-lambda-db # TODO: Use actual DB URI

mongodb:
  encrypt:
    keys:
      - version: 1
        key: ${MONGODB_ENCRYPTION_KEY}