name: "Deploy to AWS"

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy to AWS"
    runs-on: ubuntu-latest
    environment: live

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test & Build
        run: ./ci/build.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.2.7

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./terraform
        if: github.ref != 'refs/heads/main' && github.event_name == 'push'
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
